---
driver:
  name: vagrant
  customize:
    memory: 2048
  network:
    - [ "private_network", { ip: "192.168.66.4" } ]

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[cobbler::default]
    attributes:
